apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  labels:
    app: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: mr0022/scraper:latest
        ports:
        - containerPort: 5001
      livenessProbe:
        httpGet:
          path: /
          port: 5001
        initialDelaySeconds: 10
        periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  selector:
    app: scraper
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001